#!/bin/sh

### BEGIN INIT INFO
# Provides:	  uwsgi
# Required-Start:    $local_fs $remote_fs $network $syslog $named
# Required-Stop:     $local_fs $remote_fs $network $syslog $named
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts the uwsgi
# Description:       starts the uwsgi
### END INIT INFO

DAEMON=/uwsgi.sh
CWD=/packages
NAME=uwsgi
DESC=uwsgi
PID=/run/uwsgi.pid

rm -f "${PID}"
touch "${PID}"

test -x $DAEMON || exit 0

start_uwsgi() {
	start-stop-daemon --start --quiet --pidfile $PID --exec $DAEMON --user www-data # > /dev/null
 	RETVAL="$?"
	return $RETVAL
}

stop_uwsgi() {
	# kill -9 $(pidof uwsgi |awk -F " " '{print $NF}')
	# P=$(IFS=" "; pidof uwsgi | sort | IFS="\n" awk -F " " '{print $NF}')
	for p in $(IFS=" "; pidof uwsgi | sort | IFS="\n" awk -F " " '{print $NF,"\n",$(NF-1)}'); do kill -3 $p; done
	for p in $(IFS=" "; pidof uwsgi | sort | IFS="\n" awk -F " " '{print $NF,"\n",$(NF-1)}'); do kill -9 $p; done
	RETVAL="$?"
	return $RETVAL
}

# start_uwsgi

case "$1" in
	start)
		start_uwsgi
		;;
	stop)
		stop_uwsgi
		;;
	restart)
		stop_uwsgi
		sleep 3
		start_uwsgi
		;;
	status)
		P=$(pidof -s uwsgi)
		for p in $(IFS=" "; pidof uwsgi | sort | IFS="\n" awk -F " " '{print $NF,"\n",$(NF-1)}'); do echo "Running uwsgi at: ${p}"; done
		if [ -z "$P" ]; then
			exit 3	
		fi
		exit 0
		;;
esac

